name        : libtimezonemap
version     : 0.4.5
release     : 4
source      :
    - https://launchpad.net/ubuntu/+archive/primary/+files/libtimezonemap_0.4.5.tar.gz : 327e64a17c676c1bcda3b6ba3394d3d01250e5ac9a49222b9ff5737d90b15383
homepage    : https://launchpad.net/timezonemap
license     :
    - GPL-3.0
component   : desktop.library
summary     : GTK+3 timezone map widget
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - vala
description : |
    GTK+3 timezone map widget
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
