name       : libtimezonemap
version    : 0.4.6
release    : 11
source     :
    - https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/libtimezonemap/0.4.6/libtimezonemap_0.4.6.tar.gz : 0d634cc2476d8f57d1ee1864bd4f442180ae4bf040a9ae4bf73b66bbd85d7195
homepage   : https://launchpad.net/timezonemap
license    : GPL-3.0-or-later
component  : desktop.library
summary    : GTK+3 timezone map widget
description: |
    GTK+3 timezone map widget
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - vala
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
